// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfjrqdciptkhyjlrjkka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmanJxZGNpcHRraHlqbHJqa2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTU3NTQsImV4cCI6MjA2OTc5MTc1NH0.7KjyrKSS1AVM2nV1jj81joORroC7YjEmB6mZtdzXBww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});